site_name: 2020.2 - G4

repo_name: '2020.2 - G4'
repo_url: 'https://github.com/fga-eps-mds/2020-2-G4'

lang:
  - pt

extra_javascript:
  - assets/js/jquery.min.js
  - assets/js/jquery.zoom.min.js
  - assets/js/extra.js

nav:
  - Home: index.html
  - Documentação:
    - home.md
    - Guia de Contribuição: CONTRIBUTING.md
    - Equipe: team.md
  - Sprints:
    - Sprint 0:
      - Review: sprints/sprint0/sprint0_review.md
      - Planning: sprints/sprint0/sprint0_planning.md
    - Sprint 1:
      - Review: sprints/sprint1/sprint1_review.md
      - Retrospectiva: sprints/sprint1/sprint1_retrospect.md
      - Planning: sprints/sprint1/sprint1_planning.md
    - Sprint 2:
      - Review: sprints/sprint2/sprint2_review.md
      - Retrospectiva: sprints/sprint2/sprint2_retrospect.md
      - Planning: sprints/sprint2/sprint2_planning.md
    - Sprint 3:
      - Review: sprints/sprint3/sprint3_review.md
      - Planning: sprints/sprint3/sprint3_planning.md
  - Templates:
    - Planning: template_docs/template_planning.md
    - Review: template_docs/template_review.md
    - Retrospectiva: template_docs/template_retrospect.md

theme:
  name: 'material'
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  