site_name: 2020.2 - G4

repo_name: '2020.2 - G4'
repo_url: 'https://github.com/fga-eps-mds/2020-2-G4'

lang:
  - pt

extra_javascript:
  - assets/js/jquery.min.js
  - assets/js/jquery.zoom.min.js
  - assets/js/extra.js

extra_css:
  - assets/css/docs.css

nav:
  - Home: index.html
  - Documentação:
    - Home: home.md
    - Metodologia: methodology.md
    - Backlog do Projeto: backlog.md
    - Roadmap: roadmap.md
    - Identidade Visual: visual_identity.md
    - Protótipo: prototype.md
    - Documento de Visão: vision.md
    - Documento de Arquitetura: architecturedocument.md
    - Gerenciamento de Riscos: risks.md
    - EVM: evm.md
    - Equipe: team.md
    - Apresentações: presentations.md
  - Lean Inception: 
    - Introdução: leanInception/introduction.md
    - Visão De Produto: leanInception/product_vision.md
    - é - não é - faz - não faz: leanInception/is_isnot_do_donot.md
    - Objetivo do Produto: leanInception/product_purpose.md
    - Personas: leanInception/personas.md
    - Jornada do Usuário: leanInception/user_journey.md
    - BrainStorming: leanInception/brainstorming.md
    - Revisão Técnica, de Negócio, de UX: leanInception/review.md
    - Sequenciador: leanInception/sequencer.md
    - Canvas MVP: leanInception/canvas.md
  - Comunidade: 
    - Guia de Contribuição: CONTRIBUTING.md
  - Sprints:
    - Sprint 0:
      - Review: sprints/sprint0/sprint0_review.md
      - Planning: sprints/sprint0/sprint0_planning.md
    - Sprint 1:
      - Review: sprints/sprint1/sprint1_review.md
      - Retrospectiva: sprints/sprint1/sprint1_retrospect.md
      - Planning: sprints/sprint1/sprint1_planning.md
    - Sprint 2:
      - Review: sprints/sprint2/sprint2_review.md
      - Retrospectiva: sprints/sprint2/sprint2_retrospect.md
      - Planning: sprints/sprint2/sprint2_planning.md
    - Sprint 3:
      - Review: sprints/sprint3/sprint3_review.md
      - Retrospectiva: sprints/sprint3/sprint3_retrospect.md
      - Planning: sprints/sprint3/sprint3_planning.md
    - Sprint 4:
      - Planning: sprints/sprint4/sprint4_planning.md
      - Retrospectiva: sprints/sprint4/sprint4_retrospect.md
      - Review: sprints/sprint4/sprint4_review.md
    - Sprint 5:
      - Planning: sprints/sprint5/sprint5_planning.md
      - Retrospectiva: sprints/sprint5/sprint5_retrospect.md
      - Review: sprints/sprint5/sprint5_review.md
    - Sprint 6:
      - Planning: sprints/sprint6/sprint6_planning.md
  - Templates:
    - Planning: template_docs/template_planning.md
    - Review: template_docs/template_review.md
    - Retrospectiva: template_docs/template_retrospect.md

theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
  